Fix mount failure when too many layers
If the image contains too many layers the mount will fail
as
https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg1695610.html

The workable solution is to follow what docker has done for overlay2:
https://docs.docker.com/storage/storagedriver/overlayfs-driver/#how-the-overlay2-driver-works

In one word, the solution is to use a short symbolic for each layer
instead of the uuid based path

diff --git a/rpm/script/volume/pouch-volume b/rpm/script/volume/pouch-volume
--- a/rpm/script/volume/pouch-volume
+++ b/rpm/script/volume/pouch-volume
@@ -70,6 +70,13 @@ detect_docker_config() {
 
 }
 
+shorten_overlay2_layer() {
+    local origin_layers=$1
+    local lower_path=`echo ${origin_layers} | cut -f 1 -d:`
+    local shortened_layers=$(cat `dirname ${lower_path}`/lower 2>/dev/null)
+    echo ${shortened_layers}
+}
+
 usage() {
     err "Invalid usage. Usage: "
     err "\t$0 init"
@@ -132,7 +139,11 @@ domount() {
                     upperdir=`docker inspect -f '{{.GraphDriver.Data.UpperDir}}' ${cid}`
                     workdir=`docker inspect -f '{{.GraphDriver.Data.WorkDir}}' ${cid}`
                     cd ${DOCKER_GRAPH_ROOT}
-                    slowerdir=`echo ${lowerdir} | sed "s+${DOCKER_GRAPH_ROOT}+.+g"`
+                    slowerdir=$(shorten_overlay2_layer ${lowerdir})
+                    if [[ -z ${slowerdir} ]]; then
+                        err "{ \"status\": \"Failure\", \"message\": \"Unable to shorten lowerdir: ${lowerdir}\"}"
+                        exit 1
+                     fi
                     env PWD=${DOCKER_GRAPH_ROOT} mount -t overlay -o rw,lowerdir=${slowerdir},upperdir=${upperdir},workdir=${workdir} overlay2 ${mergedDir} &> /dev/null
                     if [[ $? -ne 0 ]]; then
                         err "{ \"status\": \"Failure\", \"message\": \"Failed to mount container's dir\"}"
