蚂蚁环境支持Pouch

diff --git a/rpm/script/volume/pouch-volume b/rpm/script/volume/pouch-volume
--- a/rpm/script/volume/pouch-volume
+++ b/rpm/script/volume/pouch-volume
@@ -66,8 +66,34 @@ domount() {
 				cp -rp $CTHOME$IMAGEPATH $MNTPATH
 			fi
 		else
-			err "{ \"status\": \"Failure\", \"message\": \"Pouch doesn't support copy content from image\"}"
-			exit 1
+			mergedPath=`echo ${IMAGE//\//__}`
+			mergedDir=/home/t4/pouch-volume/${mergedPath}
+			if [ ! -d $mergedDir ]; then
+				mkdir -p $mergedDir
+			fi
+			if is_empty_dir $mergedDir; then
+				# Make sure image exists
+				pouch pull $IMAGE &> /dev/null
+				cid=`pouch create --net host -l type="pouch-volume" $IMAGE`
+				if [ $? -ne 0 ]; then
+					err "{ \"status\": \"Failure\", \"message\": \"Failed to create container based on $IMAGE\"}"
+					exit 1
+				fi
+				lowerdir=`pouch inspect -f '{{.Snapshotter.Data.LowerDir}}' ${cid}`
+				upperdir=`pouch inspect -f '{{.Snapshotter.Data.UpperDir}}' ${cid}`
+				workdir=`pouch inspect -f '{{.Snapshotter.Data.WorkDir}}' ${cid}`
+				mount -t overlay -o rw,lowerdir=${lowerdir},upperdir=${upperdir},workdir=${workdir} overlay ${mergedDir} &> /dev/null
+				if [ $? -ne 0 ]; then
+					err "{ \"status\": \"Failure\", \"message\": \"Failed to mount container's dir\"}"
+					pouch rm -v ${cid} &> /dev/null
+					exit 1
+				fi
+			fi
+			if [ -d ${mergedDir} ]; then
+				cp -rp ${mergedDir}$IMAGEPATH $MNTPATH &> /dev/null
+			fi
+			umount ${mergedDir} &> /dev/null
+			pouch rm -v ${cid} &> /dev/null
 		fi
 	fi
 
@@ -117,3 +143,4 @@ case "$op" in
 esac
 
 exit 1
+
